// <auto-generated />
using System;
using GestionLlaves.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionLlaves.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionLlaves.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacidad")
                        .HasColumnType("int")
                        .HasColumnName("capacidad");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<int>("EdificioId")
                        .HasColumnType("int")
                        .HasColumnName("edificioId");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoFisico")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("DISPONIBLE")
                        .HasColumnName("estadoFisico");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Piso")
                        .HasColumnType("int")
                        .HasColumnName("piso");

                    b.Property<bool>("TieneProyector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("tieneProyector");

                    b.Property<bool>("TieneTv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("tieneTv");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EdificioId");

                    b.ToTable("aula", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Edificio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("edificio", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.HorarioAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int")
                        .HasColumnName("aulaId");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int")
                        .HasColumnName("docenteId");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<bool>("EstadoHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estadoHorario");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("grupo");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("TIME")
                        .HasColumnName("horaFin");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("TIME")
                        .HasColumnName("horaInicio");

                    b.Property<bool>("Jueves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("jueves");

                    b.Property<bool>("Lunes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("lunes");

                    b.Property<bool>("Martes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("martes");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int")
                        .HasColumnName("materiaId");

                    b.Property<bool>("Miercoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("miercoles");

                    b.Property<int>("PeriodoAcademicoId")
                        .HasColumnType("int")
                        .HasColumnName("periodoAcademicoId");

                    b.Property<bool>("Sabado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("sabado");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.Property<bool>("Viernes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("viernes");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoAcademicoId");

                    b.ToTable("horarioAcademico", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("materia", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.PeriodoAcademico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("activo");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("DATE")
                        .HasColumnName("fechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATE")
                        .HasColumnName("fechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.ToTable("periodoAcademico", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombres");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("primerApellido");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("segundoApellido");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.ToTable("persona", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AulaId")
                        .HasColumnType("int")
                        .HasColumnName("aulaId");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estadoPrestamo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaFinProgramada")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFinProgramada");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFinReal");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaInicio");

                    b.Property<int?>("HorarioAcademicoId")
                        .HasColumnType("int")
                        .HasColumnName("horarioAcademicoId");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int")
                        .HasColumnName("personaId");

                    b.Property<int?>("RecibidoPor")
                        .HasColumnType("int")
                        .HasColumnName("recibidoPor");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int")
                        .HasColumnName("reservaId");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.HasIndex("AulaId");

                    b.HasIndex("HorarioAcademicoId");

                    b.HasIndex("PersonaId");

                    b.HasIndex("RecibidoPor");

                    b.HasIndex("ReservaId");

                    b.ToTable("prestamo", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobadaPor")
                        .HasColumnType("int")
                        .HasColumnName("aprobadaPor");

                    b.Property<int>("AulaId")
                        .HasColumnType("int")
                        .HasColumnName("aulaId");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("PENDIENTE")
                        .HasColumnName("estadoReserva");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaAprobacion");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaInicio");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("justificacion");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("motivoRechazo");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("proposito");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int")
                        .HasColumnName("solicitanteId");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.HasIndex("AprobadaPor");

                    b.HasIndex("AulaId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte[]>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("VARBINARY(64)")
                        .HasColumnName("contrasenia");

                    b.Property<int>("CreadoModPor")
                        .HasColumnType("int")
                        .HasColumnName("creadoModPor");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaUltimaConexion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaUltimaConexion");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimaMod")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimaMod");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("GestionLlaves.Models.Aula", b =>
                {
                    b.HasOne("GestionLlaves.Models.Edificio", "Edificio")
                        .WithMany("Aulas")
                        .HasForeignKey("EdificioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edificio");
                });

            modelBuilder.Entity("GestionLlaves.Models.HorarioAcademico", b =>
                {
                    b.HasOne("GestionLlaves.Models.Aula", "Aula")
                        .WithMany("HorariosAcademicos")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.Persona", "Docente")
                        .WithMany("HorariosAcademicos")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.Materia", "Materia")
                        .WithMany("HorariosAcademicos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("HorariosAcademicos")
                        .HasForeignKey("PeriodoAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Docente");

                    b.Navigation("Materia");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("GestionLlaves.Models.Prestamo", b =>
                {
                    b.HasOne("GestionLlaves.Models.Aula", "Aula")
                        .WithMany("Prestamos")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.HorarioAcademico", "HorarioAcademico")
                        .WithMany("Prestamos")
                        .HasForeignKey("HorarioAcademicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionLlaves.Models.Persona", "Persona")
                        .WithMany("Prestamos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.Usuario", "RecibidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("RecibidoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionLlaves.Models.Reserva", "Reserva")
                        .WithMany("Prestamos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aula");

                    b.Navigation("HorarioAcademico");

                    b.Navigation("Persona");

                    b.Navigation("RecibidoPorUsuario");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("GestionLlaves.Models.Reserva", b =>
                {
                    b.HasOne("GestionLlaves.Models.Usuario", "AprobadaPorUsuario")
                        .WithMany()
                        .HasForeignKey("AprobadaPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GestionLlaves.Models.Aula", "Aula")
                        .WithMany("Reservas")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionLlaves.Models.Usuario", "Solicitante")
                        .WithMany("Reservas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AprobadaPorUsuario");

                    b.Navigation("Aula");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("GestionLlaves.Models.Usuario", b =>
                {
                    b.HasOne("GestionLlaves.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("GestionLlaves.Models.Usuario", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("GestionLlaves.Models.Aula", b =>
                {
                    b.Navigation("HorariosAcademicos");

                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("GestionLlaves.Models.Edificio", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("GestionLlaves.Models.HorarioAcademico", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("GestionLlaves.Models.Materia", b =>
                {
                    b.Navigation("HorariosAcademicos");
                });

            modelBuilder.Entity("GestionLlaves.Models.PeriodoAcademico", b =>
                {
                    b.Navigation("HorariosAcademicos");
                });

            modelBuilder.Entity("GestionLlaves.Models.Persona", b =>
                {
                    b.Navigation("HorariosAcademicos");

                    b.Navigation("Prestamos");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionLlaves.Models.Reserva", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("GestionLlaves.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
